<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://lh3.googleusercontent.com/pyZnwPwjSKPeSRxSMsMhLPehA8AAJVHjSynz6sJtU2CtEru1nouHuC3JWhgZ-YLIfKnEwbFlxjNsMNeBMYOJmwjMQidnDgpPGVuvyWhEBIqVneyBIyiyFnh5N1quW3vHTDZkxDfm8sLzwULDpXLwClGO-omkYLzm2wi3A3MLwqqmtDMzMa6ui9fvQsLYFgRAgBzwNty9QJowRLtVSvzjvOfJAzLgZH-R44hkyZe3W2uRDrWtc4pGxRZoRCh13tiyEdTABkqBxinWJ142p2u1OtuNyrSjhDEhAIoCDqhjKAReP830pmvhGURIzAqmrH85c_CLDYKR-O8YOn33k83FrCUXWE4vQy04W1zGL2H0gkwAQBODvT0PgAsmpx5kSLzyYvp1NEZCdGjiOiGfe9QBuh8afUq94On5vKvrISWIhmRlijRyWFc8YasY4NYr-ibSkkqiHUqenYlUOtEZ73pjFZJdYBF793oiw8w8xL9aXdgFk0VRy6wklTy3TcxSp8AnMS7EfhwI1pPJ_cuRCrwoGQLO4bLCUX2UkjAjbIP3UESYxkcWNWUWLZwB6jdOhfXYyK84OQnm3BJhDYlZl995CWLzrfD7HdoJNm-EzDzedezXT3xKechfbExgJX06kONm91MCr_xb8x5s2842CwiNswONvi2Eomc=w890-h667-no" alt="Echesurum Uche">
                        <h6>Echesurum Uche</h6>
                        <p>Software developer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/@achay009" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/achay009" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://meduim.com/@ucheachay3" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>Hi my name is Echesurum Uche ,i am a software developer and also an enthusiast, i am currently running my Bsc program in Systems Engineering at the University of lagos Akoka</p>
                        <p>I love learning new things about new things</p>
                        <p>Listening to Enya is a mood!!!</p>
                        <br/>
                        <h6>Skills</h6>
                        <p>JavaScript | c# | java </p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
